export const GET_PIZZAS = "GET_PIZZAS";
export const PIZZAS_LOADING = "PIZZAS_LOADING";
export const ADD_PIZZA_TO_CART = "ADD_PIZZA_TO_CART";
export const REMOVE_PIZZA_FROM_CART = "REMOVE_PIZZA_FROM_CART";
export const ADJUST_PIZZA_QTY = "ADJUST_PIZZA_QTY";
export const REMOVE_ALL_PIZZAS = "REMOVE_ALL_PIZZAS";
